# Generated by Django 4.1.4 on 2022-12-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Display',
        ),
    ]
