# Generated by Django 4.1.4 on 2022-12-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Display',
        ),
    ]
