# Generated by Django 4.1.4 on 2022-12-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0007_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="display",
            old_name="closing_data",
            new_name="closing_date",
        ),
    ]
