# Generated by Django 4.1.4 on 2022-12-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0008_rename_closing_data_display_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='hours',
            field=models.TextField(blank=True),
        ),
    ]
