# Generated by Django 4.1.4 on 2022-12-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0009_alter_display_hours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="display",
            old_name="type",
            new_name="location_type",
        ),
    ]
